services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: tryton
      POSTGRES_PASSWORD: tryton
      POSTGRES_DB: tryton
    volumes:
      - tryton-db-data:/var/lib/postgresql/data

  trytond:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    user: root
    depends_on:
      - db
    environment:
      TRYTOND_DATABASE_URI: postgresql://tryton:tryton@db:5432/tryton
      PYTHONPATH: /opt/trytond/modules
    ports:
      - "8000:8000"
    volumes:
      - ./trytond.conf:/etc/tryton/trytond.conf:ro
      - ./modules:/opt/trytond/modules:ro

volumes:
  tryton-db-data:
